<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Graph4_Bottom10Sites_Title_Txt</name>
   <tag></tag>
   <elementGuidId>6a2ba9dd-f7f9-48c9-8725-d416c24babfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-grid-tile[2]//figure[1]//mat-card[1]/div[@class='title-label']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.site__info-banner-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
