<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Graph1_Compl_Scr_OverTime</name>
   <tag></tag>
   <elementGuidId>47a8494a-4f8b-47cf-b1fb-813133178d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.site__info-banner-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ert-kri-overview[@class='study-comp']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
