<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Graph2_Quality_Scr_OverTime</name>
   <tag></tag>
   <elementGuidId>878f2f67-7e13-455f-b057-faffb92d92a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ert-kri-overview[@class='study-quality']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.site__info-banner-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
