<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header_Qulaity_Banner</name>
   <tag></tag>
   <elementGuidId>e5a18100-e7e4-47d4-97ea-09623af411f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ert-info-banner//h2[contains(text(),'QUALITY')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.site__info-banner-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
