<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header_MyPortfolio_Banner</name>
   <tag></tag>
   <elementGuidId>6f380a0f-903b-4446-a9ae-b78fa3872b1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@class='site__info-banner-heading']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.site__info-banner-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
