<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header_Compliance_Quality_Banner</name>
   <tag></tag>
   <elementGuidId>943409cd-3085-48e5-9cee-aba86714c763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ert-breadcrumb//mat-icon[contains(text(),&quot;chevron-right&quot;)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.site__info-banner-scores</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
